//CodePage(PorChange, [oPorJohnny, ]),
//CodePage(PorChange, [oPorVillin, ]),



scene_intro = {
	intro_1: [
		Page(spk_none, "....."),
		CodePage(PorEnter, [oPorJohnny]),
		Page(spk_johnny, "Heh. What a |V|beeeeeeaa-utiful/V/ mornin'."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "A beautiful mornin' to be good ol' |Y|Johnny Slick|W|."),
		Page(spk_johnny, "Me. |V||Y|Johnny Slick|W|/V/. The cowboy. Who rides a horse."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "That's who I am."),
		Page(spk_johnny, "Wouldn't wanna be nobody else, ain't that the truth."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "|S|Man!/S/ What a night that dun been. Can't remember the first thing about it."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "Which means it outta'ave been a darn good one, |V|hooo-ey!/V/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Except that everyone in town wants to get me now fer some reas'n."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Ah well. It's prob'ly nothin'."),
		CodePage(PorShake, [oPorJohnny]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Mustard! |S|Mustard the horse! Wake up!!/S/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Johnny needs'ya ta skip town."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Heh. All my exes live 'ere. Wouldn't wan 'em seein' me like this."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Mustard! |S|Mustard, my horse!/S/ The horse I go everywhere with!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "Where are ya? We're best buddies, ever'one knows that! It's a well-established cowboy trope!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Alright. Tactics, Johnny."),
		ChoicePage(
			Choice("Sing Mustard's song", "song"),
			Choice("Shoot the air", "gun"),
		),
	],
	song: [
		Page(spk_johnny, "Alright, here I go."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "|V|Oh my sweet baby horse.../V/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "|V|Liiiiiiike the flowers... bloomin' in the spring.../V/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "|V|You smell gooooooooood..../V/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Now that |S|always/S/ works. Where i'she?"),
		GotoPage("intro_2"),
	],
	gun: [
		Page(spk_johnny, "Alright Mustard, ya leave me no choice."),
		CodePage(audio_play_sound, [snd_GunFire, 0, false]),
		Page(spk_johnny, "Bang!"),
		CodePage(PorShake, [oPorJohnny]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		CodePage(audio_play_sound, [snd_GunFire, 0, false]),
		Page(spk_johnny, "|S|Bang!!!!/S/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(audio_play_sound, [snd_GunFire, 0, false]),
		Page(spk_johnny, "Gun sound effect."),
		Page(spk_johnny, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "Mustard know th'sound of my gun anyhow-where-whatsit."),
		Page(spk_johnny, "So... where's that horse??"),
		GotoPage("intro_2"),
	],
	intro_2: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Mustard? Are you offscreen somewhere?"),
		Page(spk_none, "They're a little further than that, Johnny."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "I know that voice..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "|S|Show yourself, villain!/S/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(PorEnter, [oPorVillin]),
		Page(spk_villin, "|V|Oh, most certainly./V/"),
		Page(spk_johnny, "|S|Villin the villain!/S/"),
		Page(spk_johnny, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "Have y'seen my horse?"),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadless]),
		Page(spk_villin, "|V|Ahaha! Indeed I have."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessSmile]),
		Page(spk_villin, "For you see... it was actually |S|I/S/ who stole your faithful horse condiment, Mustard!"),
		CodePage(PorShake, [oPorJohnny]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "..!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "Why I outta... it's time for action! Time to shoot you with my strongest weapon!"),
		CodePage(PorChange, [oPorVillin, sPorVillinScheming]),
		Page(spk_villin, "The one that you let Mustard carry last night?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "|S|No!/S/ I must've partied so hard, Mustard took my gear. But surely my SECOND strongest..."),
		CodePage(PorChange, [oPorVillin, sPorVillinSmirk]),
		Page(spk_villin, "Also with Mustard."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "...is all my gear with Mustard?"),
		Page(spk_villin, "I'm afraid so. Which means this town... now belongs to ME!"),
		CodePage(PorShake, [oPorJohnny]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "Dang it Villin! You |S|headless rapsacallion!/S/"),
		CodePage(PorChange, [oPorVillin, sPorVillinTired]),
		Page(spk_villin, "I only came by as a formality, John. I don't actually wish to talk to you any further. So..."),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessSmile]),
		Page(spk_villin, "Tata I must be going to rule the town now |V|goodbyeeeeeeee!!!/V/"),
		CodePage(PorExit, [oPorVillin]),
		Page(spk_none, "..."),
		Page(spk_johnny, "Tch!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "I'm sorry, town which I am in. Called Big Donut for some reason."),
		Page(spk_johnny, "The town filled to the brim with my exes. I dun failed you."),
		Page(spk_johnny, "..."),
		CodePage(PorFace, [oPorJohnny, LEFT]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "...no. I may be out of good options, but I'm not out of options."),
		CodePage(PorMove, [oPorJohnny, 110]),
		Page(spk_johnny, "I'm Johnny slick. Even an ex-romantic-pard'ner is still an ally if you're charmin' enough."),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_johnny, "And I sure as |S|heck/S/ can be charmin'."),
		Page(spk_johnny, "Let's pay some of my |V|acquaintances/V/ a visit..."),
		Page(spk_johnny, "Startin' with..."),
		Page(spk_johnny, "...why don' we see how Isla's doin'?"),
		CodePage(PorMove, [oPorJohnny, 400]),
		Page(spk_none, "....."),
		CodePage(NextScene),
	],
	

	isla_final_2: [
		CodePage(PorExit, [oPorJohnny]),
		CodePage(PorExit, [oPorIsla]),
	],


	
}