//CodePage(PorChange, [oPorJohnny, ]),
//CodePage(PorChange, [oPorIsla, ]),



scene_isla = {
	isla_1: [
		Page(spk_none, "....."),
		CodePage(PorEnter, [oPorJohnny]),
		Page(spk_johnny, "Well, here goes nothin'."),
		Page(spk_johnny, "Knock knock."),
		CodePage(PorEnter, [oPorIsla]),
		Page(spk_isla, "..."),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "Eheh. |V|Weeeellllllllll,/V/ look what the darn gon' did gosh dang |V|CAT/V/ dragged in."),
		Page(spk_johnny, "Hey Isla."),
		Page(spk_isla, "|V|Wheeeeeeeeeee-EW,/V/ is that really Johnny Slick at my very doorstep?"),
		ChoicePage(
			Choice("It's me", "its_me"),
			Choice("Missed me, sweetheart?", "missed_me", 1),
		),
	],
	its_me: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "It's me."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_isla, "It sure be."),
		GotoPage("isla_2"),	
	],
	missed_me: [
		Page(spk_johnny, "Missed me, sweetheart?"),
		Page(spk_isla, "..."),
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "|V|Yeeeeeesh.../V/ Johnny Slick always be flirtin', don't he?"),
		GotoPage("isla_2"),
	],
	
	
	isla_2: [
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "The same crooked wannabe cowboy look..."),
		Page(spk_isla, "The same sorry-not-sorry eyes..."),
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		Page(spk_isla, "Y'all remember how you dun left me last time your rear end was in town?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "I, uh....."),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "Don' borther. Here's what happened:"),
		ChoicePage(
			Choice("Fell out a window", "window"),
			Choice("Lost a bet", "lost_bet"),
		),
	],
	window: [
		Page(spk_isla, "You and I had just finished what I would |V|almost/V/ have called a romantic evenin'."),
		CodePage(PorMove, [oPorJohnny, 80]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "Isla, I..."),
		CodePage(PorMove, [oPorJohnny, 0]),
		Page(spk_isla, "Oh, you were showerin' me with yer praises, says I was the prettiest girl this side of the Big Donut."),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		Page(spk_isla, "Took you up to my room, we spent almost all night..."),
		Page(spk_isla, "...playin' cards."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "The romance-iest activity in the West."),
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "Right. It was |V|almost/V/ lovely."),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "'til right about 3am I hear this terrifyin' crash."),
		Page(spk_isla, "Ol' Johnny ain't so Slick now. Crawlin' out my window, slippin' on those mighty boots o'yers."),
		Page(spk_isla, "Three flights o'stairs down into the dumpster."),
		CodePage(PorShake, [oPorIsla]),
		Page(spk_isla, "|V||S|CRASH!!!/V//S/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "...heh... Good times, right Isla?"),
		Page(spk_isla, "You ran out on me."),
		GotoPage("isla_3"),
	],
	lost_bet: [
		Page(spk_isla, "You picked me up at a bar and yapped yer head off for hours about life on the open road."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_isla, "I didn't believe a word of it, o'course."),
		Page(spk_isla, "I mean, seriously, who would?"),
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "But the way you were tellin' them stories..."),
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		Page(spk_isla, "I don't please easy, Johnny, but somethin' about you."),
		Page(spk_isla, "It was worth a shot, at least."),
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "Heck, I even went so far as to imagine the two of us, alone somewhere safe....."),
		Page(spk_isla, "Chewin' bubblegum."),
		CodePage(PorMove, [oPorJohnny, 80]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Isla, we can still..."),
		Page(spk_isla, "That'd've been so nice."),
		CodePage(PorMove, [oPorJohnny, 0]),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "But then you sat down at that gosh-darned card game and a few hours later... well..."),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		Page(spk_isla, "You tried to walk back over to me with almost all yer clothes missin'."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Well, the rules of the game..."),
		CodePage(PorShake, [oPorIsla]),
		Page(spk_isla, "|S|Who loses their clothes playin' poker, Johnny?/S/"),
		Page(spk_isla, "I walked right out."),
		GotoPage("isla_3"),
	],
	
	isla_3: [
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "I've never been so immediately un-attracted-ed to a man in my entire life."),
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		Page(spk_isla, "And I once kissed Billy Bad-Breath just for the heckavit."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Isla, jus' lemme talk."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_isla, "Urgh."),
		ChoicePage(
			Choice("Polish your gun", "polish_gun", 2, sFireSpeedUp),
			Choice("Tighten your boots", "tighten_boots", 2, sMoveSpeedUp),
		),
	],
	polish_gun: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_none, "You put on your serious cowboy face and polish your gun."),
		CodePage(GetUpgrade, [UPGRADES.FIRE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Fire speed increased."),
		GotoPage("isla_4"),
	],
	tighten_boots: [
		Page(spk_none, "You bend down to tighten your boots, showing off your boot-tightening muscles."),
		CodePage(GetUpgrade, [UPGRADES.MOVE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Move speed increased."),
		GotoPage("isla_4"),
	],
	
	
	isla_4: [
		Page(spk_isla, "Always tryin'ta impress, Johnny."),
		Page(spk_johnny, "Heh. Is it workin'?"),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "Not a chance."),
		CodePage(PorMove, [oPorJohnny, 100]),
		Page(spk_johnny, "I wouldn't be here 'less it was important, Isla."),
		Page(spk_johnny, "And it's important."),
		CodePage(PorFace, [oPorIsla, RIGHT]),
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "...."),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "You're nothin' to me, Johnny."),
		ChoicePage(
			Choice("You're right", "youre_right"),
			Choice("I reckon' I'm somethin' to you", "im_somethin", 5),
		),
	],
	youre_right: [
		CodePage(PorMove, [oPorJohnny, 0]),
		Page(spk_johnny, "Tsk. You're right. But..."),
		GotoPage("isla_5"),
	],
	im_somethin: [
		Page(spk_johnny, "Naw. I reckon' I'm somethin' to you."),
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "..."),
		ChoicePage(
			Choice("...", "you_aint"),
			Choice("Enough to pour me a drink?", "pour_drink", 1, sHealthUp),
		),
	],
	you_aint: [
		CodePage(PorFace, [oPorIsla, LEFT]),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "You ain't."),
		GotoPage("isla_5"),
	],
	pour_drink: [
		Page(spk_johnny, "Somethin' enough to pour me a drink?"),
		Page(spk_isla, "..."),
		CodePage(PorFace, [oPorIsla, LEFT]),
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "Urgh. Johnny. The cowboy."),
		Page(spk_isla, "Always rootin'. Always tootin'. Always shootin'... yer shot."),
		Page(spk_isla, "I'll pour you a drink."),
		Page(spk_none, "Isla makes you a drink."),
		CodePage(GetUpgrade, [UPGRADES.HEALTH_UP]),
		Page(spk_none, "You're slick for that. Health increased."),
		GotoPage("isla_5"),

	],

	isla_5: [
		CodePage(PorMove, [oPorJohnny, 0]),
		Page(spk_johnny, "Jus' lemme tell you my woes for a time and I'll be on my way."),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		CodePage(PorFace, [oPorIsla, LEFT]),
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "Honestly, Johnny, sometimes I can't even figure out what you mean to say."),
		Page(spk_isla, "So jus' say yer nonsense and be on with it."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "I'm in a pickle, Isla."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "I came to you because you meant somethin-- you MEAN somethin' to me."),
		Page(spk_johnny, "...Mustard's missin'."),
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "Mustards... pickles... who cares, Johnny?"),
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "..."),
		Page(spk_isla, "Oh no you dun meant yer horse."),
		Page(spk_johnny, "It's... complicated."),
		CodePage(PorChange, [oPorIsla, sPorIslaNeutral]),
		Page(spk_isla, "Villin stole yer horse, didn't they?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "Yeah."),
		ChoicePage(
			Choice("I'm just a deadbeat.", "deadbeat"),
			Choice("I care about her so much.", "care_about_her", 1),
		),
	],
	deadbeat: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "I'm just a deadbeat Isla."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "I don't deserve anything from anyone."),
		GotoPage("isla_6"),
	],
	care_about_her: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "I care about her so dang much, Isla."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "I jus'... wanna get 'er back."),
		Page(spk_isla, "..."),
		GotoPage("isla_6"),
	],
	
	isla_6: [
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "Oh Johnny. Yer so pathetic."),
		Page(spk_isla, "..."),
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		Page(spk_isla, "Alright. What can I do?"),
		Page(spk_isla, "..."),
		ChoicePage(
			Choice("Seein' yer smile is enough.", "isla_final_1"),
			Choice("Kiss my gun for good luck.", "kiss_gun", 5, sDamageUp, "islaKiss"),
			Choice("Help me practise my draw.", "practise_draw", 5, sFireSpeedUp, "islaDraw"),
			Choice("Fashion advice?", "fashion", 5, sMoveSpeedUp, "islaFashion"),
			Choice("Give me your gun.", "your_gun", 12, sBigBullets, "islaGun"),
		),
	],
	isla_return_point: [
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		Page(spk_isla, "What else?"),
		ChoicePage(
			Choice("Seein' yer smile is enough.", "isla_final_1"),
			Choice("Kiss my gun for good luck.", "kiss_gun", 5, sDamageUp, "islaKiss"),
			Choice("Help me practise my draw.", "practise_draw", 5, sFireSpeedUp, "islaDraw"),
			Choice("Fashion advice?", "fashion", 5, sMoveSpeedUp, "islaFashion"),
			Choice("Give me your gun.", "your_gun", 12, sBigBullets, "islaGun"),
		),
	],
	
	
	kiss_gun: [
		Page(spk_johnny, "Wouldja... kiss my gun? For good luck?"),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "..."),
		Page(spk_isla, "Quit beatin' around the bush, Johnny. We both know I have magical kissin' powers that buff yer gun's damage."),
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		Page(spk_isla, "I'll do it."),
		Page(spk_none, "Isla kisses your gun."),
		CodePage(GetUpgrade, [UPGRADES.DAMAGE_UP]),
		Page(spk_none, "You're slick for that. Bullet damage increased."),
		Page(spk_johnny, "Heh. Thanks, darlin'."),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "It's |V|Isla,/V/ Johnny."),
		GotoPage("isla_return_point"),
	],
	practise_draw: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Help me practise my draw?"),
		CodePage(PorChange, [oPorIsla, sPorIslaMad]),
		Page(spk_isla, "Urgh. You're pathetic."),
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_none, "Isla saddles up behind you and helps you practise drawing your gun."),
		CodePage(GetUpgrade, [UPGRADES.FIRE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Fire speed increased."),
		GotoPage("isla_return_point"),
	],
	fashion: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Uhm... help me... with my boots?"),
		Page(spk_isla, "With yer boots, Johnny?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Uhm, yeah?"),
		CodePage(PorChange, [oPorIsla, sPorIslaEyeroll]),
		Page(spk_isla, "|V|Urgh..../V/ I got a nicer pair upstairs..."),
		Page(spk_none, "Isla picks out a nicer pair of boots for you."),
		CodePage(GetUpgrade, [UPGRADES.MOVE_SPEED_UP]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_none, "You're slick for that. Move speed increased."),
		GotoPage("isla_return_point"),
	],
	your_gun: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "Lend me yer gun."),
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "Johnny... how forward of you."),
		Page(spk_isla, "This is my great grandmaw's gun. She used to shoot all the boys around town with it..."),
		Page(spk_none, "Your eyes sparkle for a moment. Something in Isla changes."),
		CodePage(PorChange, [oPorIsla, sPorIslaNeutral]),
		Page(spk_isla, "Eheh. Johnny..."),
		Page(spk_isla, "There's still somethin' about you, Johnny."),
		Page(spk_isla, "Even here, at rock bottom, comin' to little-ol'-me fer help..."),
		Page(spk_isla, "Beggin' for mercy."),
		Page(spk_isla, "..."),
		CodePage(PorChange, [oPorIsla, sPorIslaConsidering]),
		Page(spk_isla, "Alright. But yer bringin' 'er back in one piece, y'hear me?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Heh. Of course, Isla. Much obliged."),
		Page(spk_none, "Isla lends you her gun."),
		CodePage(GetUpgrade, [UPGRADES.BIG_BULLETS]),
		Page(spk_none, "You're slick for that. Bullet size increased."),
		GotoPage("isla_return_point"),
	],
	
	isla_final_1: [
		Page(spk_johnny, "Seein' your beautiful smile is enough for me right now."),
		CodePage(PorChange, [oPorIsla, sPorIslaUncertain]),
		Page(spk_isla, "Alright. Be careful out there, Johnny."),
		ChoicePage(
			Choice("I will.", "i_will"),
			Choice("You'll see me again.", "last_of_me", 2),
		),
	],
	i_will: [
		Page(spk_johnny, "Heh. I will."),
		GotoPage("isla_final_2"),
	],
	last_of_me: [
		Page(spk_johnny, "You haven't seen the last of me yet, Isla."),
		Page(spk_johnny, "I'll come back. And we'll... play cards, some time."),
		Page(spk_isla, "..."),
		Page(spk_isla, "I think I'd like that, Johnny."),
		CodePage(PorChange, [oPorIsla, sPorIslaNeutral]),
		Page(spk_isla, "Now get outta here, ya no-good horse-losin' wannabe deadbeat, good-fer-nothin'...."),
		Page(spk_isla, "..."),
		Page(spk_isla, "Good luck."),
		GotoPage("isla_final_2"),
	],
	isla_final_2: [
		CodePage(PorExit, [oPorJohnny]),
		CodePage(PorExit, [oPorIsla]),
		Page(spk_none, "....."),
		CodePage(NextScene),

	],


	
}