//CodePage(PorChange, [oPorJohnny, ]),
//CodePage(PorChange, [oPorClyde, ]),


scene_clyde = {
	clyde_1: [
		Page(spk_none, "....."),
		CodePage(PorEnter, [oPorJohnny]),
		Page(spk_johnny, "Knock knock."),
		CodePage(PorEnter, [oPorClyde]),
		Page(spk_clyde, "Come in, Johnny Slick."),
		CodePage(PorMove, [oPorJohnny, 50]),
		Page(spk_johnny, "|V|Clyde!/V/ My old friend! My |V|beautiful/V/ pardner!"),
		CodePage(PorMove, [oPorJohnny, 80]),
		Page(spk_johnny, "The most gorgeous gosh-darned people-sized gun with two arms an' two legs I ever known."),
		CodePage(PorMove, [oPorJohnny, 110]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "My ol' crewmate. My detective buddy. Howya bin?"),
		CodePage(PorMove, [oPorJohnny, 0]),
		Page(spk_johnny, "..."),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Waitaminut."),
		Page(spk_johnny, "Clyde. You was expectin' me, weren't'cha?"),
		Page(spk_clyde, "I was. Isla told me you visited."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Oh... heh... so you uh.... know Isla now...?"),
		Page(spk_clyde, "Book club."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Book club?"),
		Page(spk_clyde, "Book club."),
		Page(spk_johnny, "Oh."),
		ChoicePage(
			Choice("Compliment their head.", "head"),
			Choice("Compliment their clothes.", "clothes"),
		),
	],
	head: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Your barrel's lookin' mighty fine, Clyde."),
		Page(spk_johnny, "So shiny. So |S|slick/S/. So... taken care of."),
		Page(spk_johnny, "Not to say it couldn't be a little MORE taken care of, if you catch my drift?"),
		GotoPage("clyde_2"),
	],
	clothes: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "I'm lovin' your coat, Clyde. So |V|in-teeee-lectual,/V/ so well put together."),
		Page(spk_johnny, "You're really puttin' on your best for me."),
		GotoPage("clyde_2"),

	],

	clyde_2: [
		Page(spk_clyde, "Flattery will get you nowhere, Johnny."),
		Page(spk_clyde, "Don't you remember how you left me last time we met?"),
		Page(spk_johnny, "Uhhh...."),
		Page(spk_clyde, "Well I remember."),
		ChoicePage(
			Choice("Left me for the vultures", "vultures"),
			Choice("Ratted me out", "rat"),
		),
	],
	vultures: [
		Page(spk_clyde, "We were on a mission together, you and I."),
		Page(spk_clyde, "A seven-day stakeout, miles from town."),
		Page(spk_clyde, "We were lying in wait for the chance to steal the |Y|Crown Jewel|W| of the Big Donut."),
		Page(spk_johnny, "Aw, geez. 'course I remember! You coulda written a movie 'bout that heist!"),
		Page(spk_johnny, "Good times, ey Clyde?"),
		Page(spk_clyde, "Not so good times, Johnny. We ran outta food. There was noone 'round for miles."),
		Page(spk_clyde, "Then the vultures started circling. And what did you do?"),
		Page(spk_johnny, "Uh, knowin' me, somethin' helpful?"),
		Page(spk_clyde, "..."),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		Page(spk_clyde, "You left me, Johnny."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_clyde, "Left me alone, a snack for the vultures, while you crawled your sorry posterior back to town."),
		CodePage(PorChange, [oPorClyde, sPorClydeNOOO]),
		Page(spk_clyde, "I woulda been dead for sure."),
		Page(spk_clyde, "But the vultures didn't like the taste of my metal flesh."),
		GotoPage("clyde_3"),
	],
	rat: [
		Page(spk_clyde, "We were on a mission together, you and I."),
		Page(spk_clyde, "A little investigation, trying to dig up dirt on the mayor of the Big Donut."),
		Page(spk_clyde, "A little breaking, a little entering. We got into his manor."),
		Page(spk_johnny, "Course we did! Ain't nothin' could stop the two of us, ey Clyde?"),
		Page(spk_clyde, "But then the sirens started blaring."),
		Page(spk_clyde, "The Cowboy Cops showed up outside. We knew it was only a matter of time before they Cowboy-Arrested us."),
		Page(spk_clyde, "And what did you do?"),
		Page(spk_johnny, "I saved the day, sure as sugar."),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		Page(spk_clyde, "No actually. You pinned it all on me. Ran outta that house and lied to the Cowboy-Cops."),
		CodePage(PorChange, [oPorClyde, sPorClydeNOOO]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_clyde, "Who does that, Johnny? Who lies to the Cowboy-Cops on a Wednesday afternoon like that?"),
		Page(spk_clyde, "Six months in Cowboy-Jail, I had."),
		GotoPage("clyde_3"),
	],
	clyde_3: [
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		Page(spk_clyde, "It was lame what you did, Johnny. Real lame."),
		Page(spk_johnny, "Hey, Clyde. It's still |V||S|us./S//V/ Here, I'll prove it."),
		ChoicePage(
			Choice("Be tough", "tough", 3, sDamageUp),
			Choice("Twirl your gun", "twirl", 3, sFireSpeedUp),
		),
	],
	tough: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_none, "You rip out a floorboard and crack it over your own head."),
		CodePage(PorChange, [oPorClyde, sPorClydeNOOO]),
		Page(spk_clyde, "Good golly gosh, Johnny. What was that for?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "I'm being tough. It ups my damage somehow."),
		CodePage(GetUpgrade, [UPGRADES.DAMAGE_UP]),
		Page(spk_none, "You're slick for that. Bullet damage increased."),
		GotoPage("clyde_4"),
	],
	twirl: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_none, "You take out your revolver and twirl it around your finger."),
		CodePage(GetUpgrade, [UPGRADES.FIRE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Fire speed increased."),
		GotoPage("clyde_4"),
	],
	clyde_4: [
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "See? I haven't lost my touch. And I know you ain't either."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "We're still Johnny and Clyde!"),
		Page(spk_clyde, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "|V|Johnny and Clyde!/V/"),
		Page(spk_clyde, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Yeah?"),
		Page(spk_johnny, "You're still my pardner. You're still a killer private eye."),
		CodePage(PorChange, [oPorClyde, sPorClydeNotepad]),
		Page(spk_clyde, "Actually I work as a therapist now, Johnny."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "A therapist?"),
		ChoicePage(
			Choice("That's stupid", "stupid"),
			Choice("That's nice, actually", "nice", 5),
		),
	],
	stupid: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Well that's stupid! You're a gosh-darned |V|GUN,/V/ Clyde."),
		Page(spk_johnny, "You're supposed to do the thing guns are famous for."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Lookin' real pretty."),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		Page(spk_clyde, "|V|Sigh./V/ I knew you wouldn't understand, Johnny."),
		GotoPage("clyde_5")
	],
	nice: [
		Page(spk_johnny, "Oh. That's..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "That's nice, actually."),
		Page(spk_johnny, "Why don't you... tell me about that?"),
		Page(spk_clyde, "You really wanna hear?"),
		ChoicePage(
			Choice("Yeah", "yeah"),
			Choice("Over a drink?", "drink", 3, sHealthUp),
		),
	],
	yeah: [
		Page(spk_johnny, "Yeah."),
		GotoPage("clyde_5")
	],
	drink: [
		Page(spk_johnny, "Over a drink?"),
		Page(spk_clyde, "..."),
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		Page(spk_clyde, "Haha. Johnny Slick. The |V|cowboy./V/ Who rides a |V|horse./V/"),
		Page(spk_clyde, "Alright."),
		Page(spk_none, "Clyde pours you a drink."),
		CodePage(GetUpgrade, [UPGRADES.HEALTH_UP]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_none, "You're slick for that. Health increased."),
		GotoPage("clyde_5"),
	],
	clyde_5: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_clyde, "When you're not horsin' around with you're cowboy act, stealin' hearts and stealin' coin..."),
		Page(spk_clyde, "...people around the Big Donut sometimes have REAL problems."),
		CodePage(PorChange, [oPorClyde, sPorClydeNOOO]),
		Page(spk_clyde, "Personal problems."),
		CodePage(PorChange, [oPorClyde, sPorClydeNotepad]),
		Page(spk_clyde, "I talk to people about their feelings and I don't judge 'em. That's all."),
		Page(spk_clyde, "Heck, sometimes they leave feeling better than when they arrived."),
		Page(spk_clyde, "I never got that from you when we were partners."),
		ChoicePage(
			Choice("It be what it be.", "eh"),
			Choice("I'm sorry", "sorry", 5),
		),
	],
	eh: [
		Page(spk_johnny, "There's an old cowboy sayin', Clyde."),
		Page(spk_johnny, "It be what it be."),
		Page(spk_clyde, "..."),
		Page(spk_clyde, "I've made my peace with that Johnny."),
		Page(spk_clyde, "It do be what it do be."),
		Page(spk_johnny, "Doo bee doo bee doo."),
		Page(spk_clyde, "You said it, pardner."),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_johnny, "Ha! Didja hear that? You called me your pardner."),
		Page(spk_johnny, "That means you DO still wanna help me."),
		CodePage(PorChange, [oPorClyde, sPorClydeNOOO]),
		CodePage(PorShake, [oPorClyde]),
		Page(spk_clyde, "Drat."),
		Page(spk_clyde, "I didn't mean to break like that."),
		Page(spk_johnny, "But'cha did. No going back."),
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		Page(spk_clyde, "I suppose those are the rules."),
		GotoPage("clyde_6"),
	],
	sorry: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "I'm sorry, Clyde. I done did you wrong."),
		CodePage(PorMove, [oPorJohnny, 100]),
		Page(spk_johnny, "And nothin' I do now can change that."),
		CodePage(PorMove, [oPorJohnny, 20]),
		Page(spk_johnny, "But you really were my pardner, and I hope..."),
		CodePage(PorMove, [oPorJohnny, 0]),
		Page(spk_johnny, "...in some way..."),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		Page(spk_johnny, "Maybe you can still be."),
		Page(spk_clyde, "..."),
		Page(spk_clyde, "That means a lot, Johnny."),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		Page(spk_clyde, "That stupid gosh-darned apology means a lot."),
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		Page(spk_clyde, "And it was stupid. And it |S|was/S/ gosh darned."),
		Page(spk_clyde, "Aw, shucks. Sometimes I miss those days with you too."),
		Page(spk_johnny, "Clyde..."),
		Page(spk_clyde, "Johnny and Clyde, right?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "Heh. Yeah."),
		Page(spk_johnny, "Johnny and Clyde."),
		GotoPage("clyde_6"),
	],
	clyde_6: [
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		Page(spk_clyde, "I know why you've come here. Your horse is missing."),
		Page(spk_clyde, "I'll help you if I can."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Heh. Clyde. You will?"),
		GotoPage("clyde_return_point"),
	],
	clyde_return_point: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		Page(spk_clyde, "Anything you need, Johnny."),
		ChoicePage(
			Choice("I'm good to go", "clyde_final"),
			Choice("Admire your reflection", "reflection", 5, sExtraDash, "clydeReflection"),
			Choice("Check my weapon", "weapon", 5, sFireSpeedUp, "clydeWeapon"),
			Choice("Crack my back", "back", 5, sMoveSpeedUp, "clydeBack"),
			Choice("Give me therapy", "therapy", 15, NONE, "clydeTherapy"),
		),
	],
	reflection: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "Just lemme stare at you for a little while."),
		Page(spk_clyde, "...alright Johnny. If that helps you somehow."),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		Page(spk_none, "You walk up to Clyde and stare at him."),
		Page(spk_none, "You admire your own reflection off his metal head."),
		Page(spk_none, "You're dashing."),
		CodePage(GetUpgrade, [UPGRADES.EXTRA_DASH]),
		Page(spk_none, "...and you're slick for that. Extra dash added."),
		GotoPage("clyde_return_point"),
	],
	weapon: [
		Page(spk_johnny, "Check my weapon?"),
		Page(spk_clyde, "Sure."),
		Page(spk_clyde, "..."),
		Page(spk_clyde, "Alright, checked."),
		Page(spk_clyde, "It's a gun."),
		Page(spk_johnny, "I knew it."),
		CodePage(GetUpgrade, [UPGRADES.FIRE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Fire speed increased."),
		GotoPage("clyde_return_point"),
	],
	back: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Can ya... do that thing you used to do to me?"),
		Page(spk_johnny, "After a mornin' of sleepin' on the open road?"),
		Page(spk_clyde, "..."),
		Page(spk_clyde, "Alright, Johnny."),
		Page(spk_none, "Clyde puts his arms around you and gets ready to lift you off the ground."),
		CodePage(PorShake, [oPorJohnny]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_none, "|V|CRACK./V/"),
		Page(spk_johnny, "HOO-BOY, that felt good."),
		CodePage(GetUpgrade, [UPGRADES.MOVE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Movement speed increased."),
		GotoPage("clyde_return_point"),
	],
	therapy: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Give me some of that therapy?"),
		CodePage(PorChange, [oPorClyde, sPorClydeNotepad]),
		Page(spk_clyde, "Really?"),
		Page(spk_johnny, "Uh. Yeah."),
		Page(spk_clyde, "How open-minded of you. Then let's begin."),
		Page(spk_none, "You talk to Clyde about your childhood."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "...and then my momma said, \"That's why you can't have macaroni and cheese no more.\""),
		Page(spk_clyde, "How about that. Same time next week then?"),
		Page(spk_none, "You feel lighter."),
		CodePage(GetUpgrade, [UPGRADES.MOVE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Movement speed increased."),
		CodePage(GetUpgrade, [UPGRADES.EXTRA_DASH]),
		Page(spk_none, "Also you get another dash."),
		CodePage(GetUpgrade, [UPGRADES.FIRE_SPEED_UP]),
		Page(spk_none, "And I don't care, have a better fire speed, too."),
		GotoPage("clyde_return_point"),
	],
	clyde_final: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Thanks, partner. I knew I could count on you."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_clyde, "It's no problem, Johnny. Oh, and one more thing..."),
		Page(spk_clyde, "|V|I.../V/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Yes Clyde?"),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_clyde, "|S|I...!/S/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Spit it out, Clyde!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(PorChange, [oPorClyde, sPorClydeNOOO]),
		Page(spk_clyde, "I know where Villin's hidin'."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "!!"),
		Page(spk_clyde, "It's at your ol' pal Alloy's place."),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		Page(spk_clyde, "I didn't say... because..."),
		CodePage(PorChange, [oPorClyde, sPorClyde]),
		Page(spk_clyde, "...I was jealous."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "Clyde... you'll always be a special pardner to me."),
		Page(spk_johnny, "Always. Even if sometimes I ride a horse instead of ridin'..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Uh..."),
		CodePage(PorChange, [oPorClyde, sPorClydeUp]),
		Page(spk_clyde, "Speak no more Johnny."),
		CodePage(PorChange, [oPorClyde, sPorClydeNotepad]),
		Page(spk_clyde, "It's time for a bit of introspection on my part."),
		Page(spk_clyde, "But you... you know where your horse is now."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "...Alloy's house..."),
		Page(spk_johnny, "Then that's where I'll go."),
		Page(spk_clyde, "Take care, Johnny."),
		CodePage(PorExit, [oPorClyde]),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "I'll getcha back, Mustard."),
		CodePage(PorMove, [oPorJohnny, 400]),
		Page(spk_johnny, "Jus' watch."),
		CodePage(NextScene),
	],
	
}