scene_end = {
	end_1: [
		Page(spk_none, "....."),
		CodePage(PorEnter, [oPorJohnny]),
		Page(spk_johnny, "That outta do it."),
		CodePage(PorEnter, [oPorVillin]),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessRage]),
		Page(spk_villin, "|S|URHGHHHHHHHHHHHHHSHTHHH!!!!!!!!!/S/"),
		Page(spk_villin, "|S|NO! NO! NO!/S/ This is |S|stupid!/S/ It doesn't make sense!"),
		Page(spk_villin, "You're a deadbeat! A lowlife! Who would help |S|YOU???/S/"),
		Page(spk_villin, "Everyone in this town is supposed to |S|HATE/S/ you!! I even checked!!!!!"),
		Page(spk_johnny, "Heh. The hero always beats the Villin."),
		CodePage(PorChange, [oPorVillin, sPorVillinGlare]),
		Page(spk_villin, "Stop making fun of my stupid name."),
		CodePage(PorChange, [oPorVillin, sPorVillinTired]),
		Page(spk_villin, "I know it's stupid, okay?"),
		Page(spk_villin, "I get it."),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadless]),
		Page(spk_villin, "But you don't deserve this, you hopeless flirt."),
		Page(spk_johnny, "Why not? Everyone loves Johnny Sli--"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessRage]),
		Page(spk_villin, "Shut up. I paid the people in this town an excellent wage to wander around aimlessly and shoot you on sight."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "Uh..."),
		CodePage(PorChange, [oPorVillin, sPorVillinScheming]),
		Page(spk_villin, "They had it good, I'm tellin' you."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Hey, don't pin this on me. You're the evil one who wanted to rule the town."),
		Page(spk_johnny, "You may have been acting nice, but you woulda turned on 'em eventually!"),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadless]),
		Page(spk_villin, "That's not the |S|point!/S/"),
		Page(spk_villin, "The point is, I worked hard! I put in the hours! I stole your stupid horse! But you won anyway!"),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessRage]),
		Page(spk_villin, "I just wanna know why such an |S|idiot/S/ gets to come out the winner..."),
		Page(spk_villin, "...and I'm still left with NOTHING!"),
		Page(spk_johnny, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "Villin..."),
		Page(spk_johnny, "...at the end of the day, you lost. That much is true."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "But you don't have nothing."),
		ChoicePage(
			Choice("You have therapy", "therapy_ending"),
			Choice("You have me", "flirt_ending", 30),
		),
	],
	therapy_ending: [
		Page(spk_johnny, "You have therapy."),
		Page(spk_villin, "What?"),
		CodePage(PorChange, [oPorVillin, sPorVillinGlare]),
		CodePage(PorExit, [oPorJohnny]),
		CodePage(PorEnter, [oPorLeftClyde]),
		Page(spk_left_clyde, "Hi Villin."),
		CodePage(PorChange, [oPorVillin, sPorVillinSmirk]),
		Page(spk_villin, "Hello right-facing Clyde."),
		Page(spk_left_clyde, "You sure dun did cause a lotta trouble here in the Big Donut."),
		CodePage(PorChange, [oPorVillin, sPorVillinGlare]),
		Page(spk_villin, "Stupid town. Stupid name."),
		Page(spk_left_clyde, "You sure call a lotta things stupid. We should talk about that."),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadless]),
		Page(spk_villin, "I don't wanna talk. I just wanna take over a town..."),
		CodePage(PorChange, [oPorVillin, sPorVillinGlare]),
		Page(spk_villin, "...and maybe make Johnny Slick eat dirt."),
		CodePage(PorChange, [oPorLeftClyde, sPorClydeNotepad]),
		Page(spk_left_clyde, "I know, I know. Desires are something we all have as people. It's normal."),
		CodePage(PorChange, [oPorLeftClyde, sPorClydeUp]),
		Page(spk_left_clyde, "I, too, want to make Johnny Slick eat dirt."),
		CodePage(PorChange, [oPorLeftClyde, sPorClydeNotepad]),
		Page(spk_left_clyde, "You're a normal person with normal wants and normal problems."),
		Page(spk_villin, "Shut up."),
		CodePage(PorMove, [oPorLeftClyde, 80]),
		Page(spk_left_clyde, "And I promise, if you tell me a bit about them... I won't judge."),
		CodePage(PorChange, [oPorVillin, sPorVillinTired]),
		Page(spk_villin, "..."),
		Page(spk_left_clyde, "..."),
		CodePage(PorChange, [oPorVillin, sPorVillinScheming]),
		Page(spk_villin, "..."),
		Page(spk_left_clyde, "..."),
		CodePage(PorChange, [oPorVillin, sPorVillinGlare]),
		Page(spk_villin, "...you won't?"),
		Page(spk_left_clyde, "Nope. Honest."),
		Page(spk_villin, "..."),
		CodePage(PorChange, [oPorVillin, sPorVillin]),
		Page(spk_villin, "When I was younger, my mom saw me playin' with my model houses... rulin' over them like a little tyrant..."),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadless]),
		Page(spk_villin, "She got so mad at me, she chopped my head off."),
		Page(spk_left_clyde, "Interesting. Tell me more about that....."),
		CodePage(PorExit, [oPorVillin]),
		CodePage(PorExit, [oPorLeftClyde]),
		Page(spk_none, "....."),
		CodePage(PorEnter, [oPorJohnny]),
		GotoPage("end_final"),
	],

	flirt_ending: [
		Page(spk_johnny, "You have me."),
		CodePage(PorChange, [oPorVillin, sPorVillin]),
		Page(spk_villin, "..."),
		Page(spk_johnny, ";)"),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadless]),
		Page(spk_villin, "No. Nononono. Stop. Don't even--"),
		Page(spk_johnny, "You know, you really do have a gorgeous pair of eyes on your gorgeous |V|de-tatchable/V/ head."),
		CodePage(PorShake, [oPorVillin]),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessRage]),
		Page(spk_villin, "|S|Johnnythecowboywhoridesahorsedontyoustart---/S/"),
		Page(spk_johnny, "And that cute little dress? I mean |V|come on,/V/ it's like you were DESIGNED to be on-screen with Johnny--"),
		CodePage(PorShake, [oPorVillin]),
		Page(spk_villin, "|S|Don't you flirt with me, Johnny Slick!/S/"),
		Page(spk_johnny, "And let's not forget that adorable little evil plan'o'yours..."),
		CodePage(PorShake, [oPorVillin]),
		Page(spk_villin, "|S|..!/S/"),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadless]),
		Page(spk_villin, "..."),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessBlush]),
		Page(spk_villin, "Wait you thought my evil plan was cute??????"),
		Page(spk_johnny, "So cute."),
		Page(spk_villin, "(-v-)"),
		Page(spk_johnny, "Uh, what does that mean?"),
		Page(spk_villin, "It's my little being-embarassed emoji."),
		CodePage(PorMove, [oPorJohnny, 100]),
		Page(spk_johnny, "Oh cool, so my flirtin' is workin' then?"),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessRage]),
		Page(spk_villin, "No..."),
		Page(spk_johnny, "Maybe?"),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessBlush]),
		Page(spk_villin, "...maybe..."),
		CodePage(PorChange, [oPorVillin, sPorVillinHeadlessSmile]),
		Page(spk_villin, "...maybe |S|take me out to dinner first, Johnny Slick!/S/"),
		CodePage(PorMove, [oPorJohnny, 140]),
		Page(spk_johnny, "That can be arranged, Villin ;)"),
		CodePage(PorMove, [oPorJohnny, 0]),
		Page(spk_johnny, "But first..."),
		Page(spk_villin, "..."),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		Page(spk_johnny, "Gimme a minute, will ya?"),
		CodePage(PorChange, [oPorVillin, sPorVillinGlare]),
		Page(spk_villin, "|V|...okay............../V/"),
		CodePage(PorExit, [oPorVillin]),
		Page(spk_none, "....."),
		GotoPage("end_final"),
	],
	end_final: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "GET OVER HERE, YA DING-DONG |S|HORSE!!!/S/"),
		CodePage(PorEnter, [oPorMustard]),
		Page(spk_none, "....."),
		Page(spk_mustard, "Nae."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "Mustard! I'm so glad you're alive and safe."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "And I'm sorry."),
		Page(spk_johnny, "I got so caught up in my parytin', I lost sight of what was truly important."),
		Page(spk_mustard, "Nae."),
		Page(spk_johnny, "That's right. It was..."),
		Page(spk_johnny, "...you."),
		Page(spk_mustard, "Nae."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "|S|HAHA, RIGHT???/S/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "I'll never party so hard I forget my horse again."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "Now, what do you say we ditch this town and never come back?"),
		Page(spk_mustard, "Nae."),
		Page(spk_johnny, "No, you're right. I have friends here. People who mean somethin' to me."),
		Page(spk_johnny, "I should at least stick around a little longer, right?"),
		Page(spk_mustard, "Nae."),
		Page(spk_johnny, "Yeah. Well, looks like that's everythin'."),
		ChoicePage(
			Choice("Ride into sunset", "end_end"),
			Choice("Flirt with the horse", "end_horse", 99),
		),
	],
	
	end_end: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Let's ride off into the sunset, Mustard."),
		Page(spk_mustard, "Nae."),
		Page(spk_johnny, "|V|YEEEEEEEEEEEEEEEEE HAWWW!!!!!/V/"),
		CodePage(NormalEnding),
	],
	end_horse: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Say, Mustard. We bin' through a lot together."),
		Page(spk_johnny, "Maybe it's the adrenaline talkin', but I just..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "...the way your eyes glisten in the moonlight..."),
		Page(spk_johnny, "...the way you flick your mane..."),
		Page(spk_johnny, "...the way you move... almost like an |S|animal/S/..."),
		Page(spk_mustard, "Ok Johnny so Imma stop you right there--"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "Ew you talk?"),
		Page(spk_mustard, "You really flirt too much, man."),
		Page(spk_mustard, "What did you save up all your in-game gift currency flirt-points to get the special HORSE ending or somethin'?"),
		Page(spk_johnny, "Mustard, I don't know what you--"),
		Page(spk_mustard, "Ok, well now you get it:"),
		CodePage(HorseEnding),
	],
}

function NormalEnding() {
	ClearTextHandler();
	SlideTransition(TRANS_MODE.GOTO, rNormalEnding);
}

function HorseEnding() {
	ClearTextHandler();
	room_goto(rHorseEnding);
}