scene_alloy = {
	alloy_1: [
		CodePage(PorEnter, [oPorJohnny]),
		Page(spk_johnny, "Alloy! Open up. I know what you're doing."),
		CodePage(PorEnter, [oPorAlloy]),
		Page(spk_alloy, ":)"),
		Page(spk_johnny, "Alloy! Dang it, why are you doin' this?"),
		Page(spk_johnny, "You're too dang handsome to be harborin' a villain like Villin!"),
		Page(spk_johnny, "You remember me, your ol' pal Johnny! The cowboy! Who rides a horse!"),
		Page(spk_alloy, ":)"),
		Page(spk_johnny, "You remember me... from... uh..."),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "Wait how do I know you?"),
		Page(spk_alloy, "Oh Johnny. The cowboy. Who rides a horse."),
		Page(spk_alloy, "You drank my drink down at the bar. When you thought I wasn't looking."),
		Page(spk_alloy, "You didn't care. You've never cared for a single person your entire life whose name wasn't Johnny Slick."),
		Page(spk_alloy, "And so I cast a spell on you to turn you into my unquestioning servant and forced you to do my bidding for one thousand years."),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "Yeah I don't rem'ber that ever happening."),
		Page(spk_alloy, "Of course you do not. Because of what happened next."),
		ChoicePage(
			Choice("You flirted mercilessly", "flirt"),
			Choice("You were too slick", "slick"),
		),
	],
	
	flirt: [
		Page(spk_alloy, "You flirted with me mercilessly."),
		Page(spk_alloy, "My clothes. My face. My house. Even my mannerisms."),
		Page(spk_alloy, "Nothing was safe from your constant barrage of flirtation."),
		Page(spk_alloy, "I was bombarded with compliments and quasi-romantic well-wishes in continuous time."),
		Page(spk_alloy, "You placed me on the ultimate pedastal."),
		GotoPage("alloy_2"),	
	],
	slick: [
		Page(spk_alloy, "You were simply too slick."),
		Page(spk_alloy, "The way you did everything I asked so effortlessly."),
		Page(spk_alloy, "The way you cooked me food with mathematical perfection and kept the house spotless to within nano-quantiles of even dust."),
		Page(spk_alloy, "The way that my life became so completely devoid of burden with you around."),
		Page(spk_alloy, "You had reached... an ultimate level of slick."),
		GotoPage("alloy_2"),
	],
	alloy_2: [
		Page(spk_alloy, "And so naturally I had to terminate the situation. And wipe your memories."),
		Page(spk_johnny, "Heh. Good ol' Johnny Slick. Always reaching |V|unfathomable/V/ levels of charm."),
		Page(spk_alloy, "My only desire was to perfectly recreate our pre-existing dynamic with one alteration:"),
		Page(spk_alloy, "It should be free from the power-imbalance from you being placed under my spell."),
		Page(spk_alloy, "And now, by performing the small moral sacrifice of harbouring a villain within my home, I have achieved my goal:"),
		Page(spk_alloy, "Johnny Slick will once again exist to please me."),
		ChoicePage(
			Choice("I have no idea what's going on.", "clueless"),
			Choice("Challenge accepted.", "challenge"),
		),
	],
	clueless: [
		Page(spk_johnny, "I have no idea what's going on."),
		Page(spk_johnny, "But if pleasin' you is what it takes to get to my horse..."),
		Page(spk_johnny, "Then Johnny's gonna hafta bust out the ol' slick once again."),
		GotoPage("alloy_return_point"),
	],
	challenge: [
		Page(spk_johnny, "Challenge accepted."),
		Page(spk_johnny, "If pleasin' you is what it takes to get my horse back..."),
		Page(spk_johnny, "Then |S|please/S/ you I shall!"),
		GotoPage("alloy_return_point"),
	],
	
	alloy_return_point: [
		Page(spk_alloy, "Compliment me, you fool."),
		ChoicePage(
			Choice("I'm good to go", "clyde_final", "alloy_final"),
			Choice("Your hair is cute", "hair", 7, sExtraDash, "alloyHair"),
			Choice("Your hat is adorable", "hat", 7, sHealthUp, "alloyHat"),
			Choice("Your spellbook well-crafted", "spellbook", 7, sDamageUp, "alloySpellbook"),
			Choice("Your plan worked perfectly", "plan", 7, sFireSpeedUp, "alloyPlan"),
		),
	],
	hair: [
		Page(spk_johnny, "Your hair is too cute!"),
		Page(spk_johnny, "I just wanna fluff those little buns all day long!"),
		Page(spk_alloy, "|S|Yes!/S/ My effort has not gone unnoticed!"),
		CodePage(GetUpgrade, [UPGRADES.EXTRA_DASH]),
		Page(spk_none, "Alloy injects you with power. Gained an extra dash."),
		GotoPage("alloy_return_point"),
	],
	hat: [
		Page(spk_johnny, "Your hat reminds me of a powerful wizard!"),
		Page(spk_johnny, "You're probably magic enough to crack me in two with your mind alone!"),
		Page(spk_alloy, "|S|I am indeed a very powerful sorceress./S/"),
		CodePage(GetUpgrade, [UPGRADES.HEALTH_UP]),
		Page(spk_none, "Alloy injects you with power. Health increased."),
		GotoPage("alloy_return_point"),
	],
	spellbook: [
		Page(spk_johnny, "Your spellbook is so well-crafted!"),
		Page(spk_johnny, "You're a real artisan in the making!"),
		Page(spk_alloy, "It's hollowed out on the inside. I use it to keep my gun hidden."),
		CodePage(GetUpgrade, [UPGRADES.DAMAGE_UP]),
		Page(spk_none, "Alloy injects you with power. Bullet damage increased."),
		GotoPage("alloy_return_point"),
	],
	plan: [
		Page(spk_johnny, "Your plan has gone perfectly!"),
		Page(spk_johnny, "I am completely under your spell!"),
		Page(spk_alloy, "|S||V|All/S//V/ my plans go perfectly."),
		CodePage(GetUpgrade, [UPGRADES.FIRE_SPEED_UP]),
		Page(spk_none, "Alloy injects you with power. Fire speed increased."),
		GotoPage("alloy_return_point"),
	],
	alloy_final: [
		Page(spk_johnny, "I'm good to go."),
		Page(spk_alloy, "Go forth, Johnny Slick. The cowboy. Who rides a horse."),
		Page(spk_alloy, "Just to see you rise again... this has all been worthwhile."),
		CodePage(PorExit, [oPorAlloy]),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "|S|Villin!/S/"),
		CodePage(PorEnter, [oPorVillin]),
		Page(spk_villin, "Johnny Slick. The cowboy. Who rides a horse."),
		Page(spk_villin, "Do you |V|REALLY/V/ think you can defeat me?"),
		Page(spk_villin, "This is |V|MY/V/ town now. Haven't you seen all my little guys?"),
		Page(spk_johnny, "I've dealt with your guys, Villin. And now..."),
		Page(spk_villin, "What, you're gonna deal with me?"),
		Page(spk_villin, "You? You useless, pathetic excuse for a man."),
		Page(spk_johnny, "...I'm gonna deal with you."),
		Page(spk_villin, "No you're not I just said that."),
		Page(spk_johnny, "Villin?"),
		Page(spk_villin, "Yes?"),
		Page(spk_johnny, "It's Johnny-ing time."),
		Page(spk_villin, "|V|Do your worst, Johnny Slick!"),
		CodePage(PorExit, [oPorJohnny]),
		CodePage(PorExit, [oPorAlloy]),
	],
	
}