
scene_alloy = {
	alloy_1: [
		Page(spk_none, "....."),
		CodePage(PorEnter, [oPorJohnny]),
		Page(spk_johnny, "Alloy! Open up. I know what you're doing."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Alloy! Dang it, why are you doin' this?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "You're too dang handsome to be harborin' a villain like Villin!"),
		CodePage(PorEnter, [oPorAlloy]),
		Page(spk_alloy, ":)"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "You remember me, your ol' pal Johnny! The cowboy! Who rides a horse!"),
		Page(spk_alloy, ":)"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "You remember me... from... uh..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "Wait how do I know you?"),
		Page(spk_johnny, "I know I know you. Your name's Alloy. I know where ya live an' everythin'"),
		Page(spk_johnny, "But... where did we meet...? What do you..."),
		Page(spk_alloy, "Oh Johnny. The cowboy. Who rides a horse."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "You drank my drink down at the Big Donut Bar. When you thought I wasn't looking."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPissed]),
		Page(spk_alloy, "You didn't care. You've never cared for a single person your entire life whose name wasn't Johnny Slick."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "And so I cast a spell on you to turn you into my unquestioning servant and forced you to do my bidding for one thousand years."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "Yeah, no. I don't rem'ber that ever happening."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPissed]),
		Page(spk_alloy, "Of course you do not. Because of what happened next."),
		ChoicePage(
			Choice("You flirted mercilessly", "flirt"),
			Choice("You were too slick", "slick"),
		),
	],
	
	flirt: [
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "You flirted with me mercilessly."),
		Page(spk_alloy, "My clothes. My face. My house. Even my mannerisms."),
		Page(spk_alloy, "Nothing was safe from your constant barrage of flirtation."),
		Page(spk_alloy, "I was bombarded with compliments and quasi-romantic well-wishes in continuous time."),
		Page(spk_alloy, "You placed me on the ultimate pedastal."),
		GotoPage("alloy_2"),	
	],
	slick: [
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "You were simply too slick."),
		Page(spk_alloy, "The way you did everything I asked so effortlessly."),
		Page(spk_alloy, "The way you cooked me food with mathematical perfection and kept the house spotless to within nano-quantiles of even dust."),
		Page(spk_alloy, "The way that my life became so completely devoid of burden with you around."),
		Page(spk_alloy, "You had reached... an ultimate level of slick."),
		GotoPage("alloy_2"),
	],
	alloy_2: [
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "And so naturally I had to terminate the situation. And wipe your memories."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "Heh. Good ol' Johnny Slick. Always reaching |V|unfathomable/V/ levels of charm."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		Page(spk_johnny, "Waitaminut. You're magic folk?"),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPleasantSurprise]),
		Page(spk_alloy, "Yes."),
		Page(spk_johnny, "..."),
		Page(spk_johnny, "Ain't this a cowboy town?"),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "Quiet you."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "You left me with an unforgettable experience."),
		Page(spk_alloy, "But it was not fair. It was not |S|earned./S/"),
		Page(spk_alloy, "Since then, my only desire has been to perfectly recreate our pre-existing dynamic."),
		Page(spk_alloy, "But there should be one key alteration:"),
		CodePage(PorChange, [oPorAlloy, sPorAlloyCheeky]),
		Page(spk_alloy, "You must be here by choice."),
		Page(spk_johnny, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyHumility]),
		Page(spk_johnny, "Uh... I don't get it."),
		Page(spk_johnny, "Weren't you... uh... happy? Before? With me?"),
		Page(spk_johnny, "(Assumin' you're even tellin' me the truth...)"),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "Haha. Of course Johnny Slick wouldn't understand."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPissed]),
		Page(spk_alloy, "Consent is critical. What good is a victory of desire if you do not desire to be here?"),
		Page(spk_alloy, "And now, by performing the small moral sacrifice of harbouring a villain within my home, I have achieved my goal:"),
		CodePage(PorChange, [oPorAlloy, sPorAlloyCheeky]),
		Page(spk_alloy, "Johnny Slick will once again exist to please me."),
		ChoicePage(
			Choice("I have no idea what's going on.", "clueless"),
			Choice("Challenge accepted.", "challenge"),
		),
	],
	clueless: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "I have no idea what's going on."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "But if pleasin' you is what it takes to get to my horse..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Then Johnny's gonna hafta bust out the ol' slick once again."),
		GotoPage("alloy_return_point"),
	],
	challenge: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Challenge accepted."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "If pleasin' you is what it takes to get my horse back..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Then |S|please/S/ you I shall!"),
		GotoPage("alloy_return_point"),
	],
	
	alloy_return_point: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "Compliment me, you fool."),
		ChoicePage(
			Choice("More flirt options!", "alloy_return_point_2"),
			Choice("Your hair is cute", "hair", 7, sExtraDash, "alloyHair"),
			Choice("Your hat is adorable", "hat", 7, sHealthUp, "alloyHat"),
			Choice("You talk real nice", "spellbook", 7, sDamageUp, "alloySpellbook"),
			Choice("Your plan worked perfectly", "plan", 7, sFireSpeedUp, "alloyPlan"),
		),
	],
	alloy_return_point_2: [
		Page(spk_none, "More flirting!"),
		ChoicePage(
			Choice("More flirt options!", "alloy_return_point"),
			Choice("Your smile is everything", "smile", 7, sMoveSpeedUp, "alloySmile"),
			Choice("Your mask is exquisite", "mask", 10, sInvulernableDash, "alloyMask"),
			Choice("I'm good to go", "alloy_final"),
		),
	],
	hair: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Your hair is too cute!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Such a |V|gor-geeee-ous/V/ shade o'green."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "I ain't never seen a look so foreign an' exotic in all my days!"),
		Page(spk_johnny, "It's like you're from some alternate reality!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPleasantSurprise]),
		Page(spk_alloy, "Oh Johnny. Do not be concerned with The Lore, for it is beyond your comprehension."),
		Page(spk_johnny, "I just wanna fluff those little buns all day long!"),
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "Yes indeed. My effort has not gone unnoticed."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_none, "Alloy injects you with power."),
		CodePage(GetUpgrade, [UPGRADES.EXTRA_DASH]),
		Page(spk_none, "You're slick for that. Gained an extra dash."),
		GotoPage("alloy_return_point"),
	],
	hat: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Your hat is just adorable! It reminds me of a powerful wizard!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "Mind you, I've never seen a real wizard before. But that's how cute your hat is!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "It makes me imagine!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPleasantSurprise]),
		Page(spk_alloy, "I am indeed a very powerful sorceress."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "You're probably magic enough to crack me in two with your mind alone!"),
		Page(spk_johnny, "And you'll do it with that cute little bow on your head."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "|V||S|Simply DIVINE!!!/V//S/"),
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "Compliment accepted."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_none, "Alloy injects you with power."),
		CodePage(GetUpgrade, [UPGRADES.HEALTH_UP]),
		Page(spk_none, "You're slick for that. Health increased."),
		GotoPage("alloy_return_point"),
	],
	spellbook: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "You talk real nice!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "All soft and mushy, yet |V|clear and articulate!/V/"),
		Page(spk_johnny, "How do you do it?"),
		Page(spk_alloy, "I come from a realm beyond the stars."),
		Page(spk_alloy, "My native tongue is incomprehensible to you."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyCheeky]),
		Page(spk_alloy, "If you heard it you would surely perish instantly."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "Therefore I practised your earthly language before I arrived."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "|S|Such a gesture!/S/ You're so |V|considerate,/V/ any cowboy, cowgirl or non-cow-binary would be lucky to hav' ya!"),
		Page(spk_alloy, "An excellent compliment, Johnny."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_none, "Alloy injects you with power."),
		CodePage(GetUpgrade, [UPGRADES.DAMAGE_UP]),
		Page(spk_none, "You're slick for that. Bullet damage increased."),
		GotoPage("alloy_return_point"),
	],
	plan: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Your plan has gone perfectly!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "You wanted me here, at your mercy, puffin' you up  out of my own free will."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "And you've got it! Not only that, but I'm |S|enjoyin' myself!/S/"),
		Page(spk_alloy, "Oh Johnny. This is romance unlike any I have ever experienced."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyCheeky]),
		Page(spk_alloy, "Since I have never experienced it before."),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "And never will again."),
		Page(spk_johnny, "I am completely under your spell!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "Wait, why never again?"),
		CodePage(PorChange, [oPorAlloy, sPorAlloyCheeky]),
		Page(spk_alloy, "My plan HAS gone perfectly."),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "Now be silenced and become stronger."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_none, "Alloy injects you with power."),
		CodePage(GetUpgrade, [UPGRADES.FIRE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Fire speed increased."),
		GotoPage("alloy_return_point"),
	],
	smile: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Your smile... is |S|everything!/S/"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "Your cheeky expression... knowing you've got me right where you want me..."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "The intensity is beyond anything I've ever seen in a woman!"),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPissed]),
		Page(spk_alloy, "Make no mistake, Johnny Slick. I am no woman."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPleasantSurprise]),
		Page(spk_alloy, "But you are within a tolerable margin of error."),
		Page(spk_alloy, "I am still flattered. You have earned this gift."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_none, "Alloy injects you with power."),
		CodePage(GetUpgrade, [UPGRADES.MOVE_SPEED_UP]),
		Page(spk_none, "You're slick for that. Move speed increased."),
		GotoPage("alloy_return_point"),
	],
	mask: [
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "Your mask is exquisite!"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyTough]),
		Page(spk_johnny, "Made from the finest whatsits, forged in the fieriest doozits..."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyPleasantSurprise]),
		Page(spk_alloy, "Oh Johnny. Your astoundingly weak grasp on even basic Cowboy-ese is so charming."),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "My mask is forged out of pure |Y|Star Energy|W|."),
		Page(spk_alloy, "It is an enchantment so powerful that simply existing in the same realm as you weakens your brain chemistry..."),
		Page(spk_alloy, "And makes you into a hopeless romantic."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyCheeky]),
		Page(spk_alloy, "That's canon, by the way."),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyNeutral]),
		Page(spk_johnny, "All I know is, you look beautiful with it on, and beautiful with it off."),
		CodePage(PorChange, [oPorAlloy, sPorAlloySurprised]),
		Page(spk_alloy, "..."),
		Page(spk_none, "Alloy blushes for a moment. And then..."),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "Take this, Johnny."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyShocked]),
		CodePage(PorShake, [oPorJohnny]),
		Page(spk_none, "Alloy injects you with power."),
		CodePage(GetUpgrade, [UPGRADES.INVULNERABLE_DASH]),
		Page(spk_none, "You're slick for that. All dashes are now invulnerable."),
		GotoPage("alloy_return_point"),
	],
	alloy_final: [
		Page(spk_johnny, "Alright. No more flirtin'."),
		Page(spk_johnny, "I'm good to go."),
		Page(spk_johnny, "My horse is out there. And they need me."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyHappy]),
		Page(spk_alloy, "Go forth, Johnny Slick. The cowboy. Who rides a horse."),
		CodePage(PorChange, [oPorAlloy, sPorAlloyCheeky]),
		Page(spk_alloy, "This has all been worth my while."),
		CodePage(PorChange, [oPorAlloy, sPorAlloy]),
		Page(spk_alloy, "The fall. The confusion. The long explanations. The endless dialogue."),
		Page(spk_johnny, "Endless."),
		Page(spk_alloy, "Just to see you rise again..."),
		Page(spk_alloy, "I will remember this, a thousand years from now, in a solar system beyond the reach of light itself."),
		Page(spk_johnny, "|V|Yeah!/V/"),
		Page(spk_alloy, "But for now my role has ended."),
		Page(spk_alloy, "Goodbye, Johnny Slick."),
		CodePage(PorExit, [oPorAlloy]),
		Page(spk_johnny, "..."),
		CodePage(StopMusic),
		CodePage(PorMove, [oPorJohnny, 140]),
		Page(spk_none, "You take a moment to steel yourself."),
		Page(spk_johnny, "Have I gone dun right by my horse?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "Have I gone dun right by... my friends?"),
		Page(spk_johnny, "My partners?"),
		Page(spk_johnny, "Romantic or otherwise?"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySus]),
		Page(spk_johnny, "(It's a big ambiguous really. But |V|MAN/V/ I love to flirt...)"),
		CodePage(PorChange, [oPorJohnny, sPorJohnnySad]),
		Page(spk_johnny, "Have I done right by... myself?"),
		CodePage(PorFace, [oPorJohnny, LEFT]),
		Page(spk_johnny, "I'm Johnny Slick, but... am I Johnny Slick Enough?"),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		Page(spk_johnny, "Heh."),
		Page(spk_johnny, "There's only one way this can end, isn't there?"),
		CodePage(PorMove, [oPorJohnny, 0]),
		Page(spk_johnny, "A climactic battle. More intense even than the last three I've fought today!"),
		CodePage(PorFace, [oPorJohnny, RIGHT]),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyLament]),
		Page(spk_johnny, "(And they were...... so intense.)"),
		Page(spk_johnny, "No more stallin'. Here we go."),
		CodePage(PorChange, [oPorJohnny, sPorJohnnyMouth]),
		Page(spk_johnny, "|S|Villin!/S/"),
		CodePage(PorEnter, [oPorVillin]),
		Page(spk_villin, "....."),
		Page(spk_villin, "Johnny Slick. The cowboy. Who rides a horse."),
		Page(spk_villin, "Do you |V|REALLY/V/ think you can defeat me?"),
		Page(spk_villin, "This is |V|MY/V/ town now. Haven't you seen all my little guys?"),
		Page(spk_johnny, "I've dealt with your guys, Villin. And now..."),
		Page(spk_villin, "What, you're gonna deal with me?"),
		Page(spk_villin, "You? You useless, pathetic excuse for a man."),
		Page(spk_johnny, "...I'm gonna deal with you."),
		Page(spk_villin, "No you're not I just said that."),
		Page(spk_johnny, "Villin?"),
		Page(spk_villin, "Yes?"),
		Page(spk_johnny, "You've put in the work, haven't you?"),
		Page(spk_villin, "I think so, yes."),
		Page(spk_johnny, "Looks like you get to hear my signature catchphrase."),
		Page(spk_johnny, "The one I say all the time."),
		Page(spk_villin, "You're bluffing."),
		Page(spk_johnny, "I ain't."),
		Page(spk_villin, "Tch. Let's hear it, then."),
		ChoicePage(
			Choice("It's Johnny-ing time.", "jt"),
			Choice("I'm Slick for this.", "js"),
			Choice("YEE HAW.", "jy"),
			Choice(";)", "jw"),
		),
	],
	jt: [
		Page(spk_johnny, "It's Johnny-ing time."),
		GotoPage("villin"),
	],
	js: [
		Page(spk_johnny, "I'm Slick for this."),
		GotoPage("villin"),
	],
	jy: [
		Page(spk_johnny, "|V|YEEEEEEEEEEEEEEEEE HAWWW!!!!!/V/"),
		GotoPage("villin"),
	],
	jw: [
		Page(spk_johnny, ";)"),
		Page(spk_villin, "Are you gonna say it?"),
		Page(spk_johnny, "I just did."),
		Page(spk_villin, "No you didn't you winked."),
		Page(spk_johnny, "That's my catchphrase."),
		Page(spk_villin, "..."),
		Page(spk_villin, "Whatever."),
		GotoPage("villin"),
	],
	
	villin: [
		Page(spk_villin, "|V|Do your worst, Johnny Slick!/V/"),
		CodePage(PorExit, [oPorJohnny]),
		CodePage(PorExit, [oPorAlloy]),
		Page(spk_none, "....."),
		CodePage(NextScene),
	],
	
}