/// @description Init

hsp = 0;
vsp = 0;
grv = 0.2;
walksp = 2;
currentwalksp = 0;
canJump = true;
jumpBuffer = 0;
airborne = false;
shootTimer = 0;
shootCooldown = 10;
accel = 0.25;
spawnDust = 0;
dashing = false;
airDash = false;
dashOver = false;
initialRunDir = 0;
hit = false;
invulnerable = 0;